### PR TITLE
Updating this plugin

### PR DESCRIPTION
**Pull request by laughedelic**
Hi @melted!

There is this repo: [laughedelic/sublime-idris](https://github.com/laughedelic/sublime-idris), which contains improved syntax definition and some other functionality (not much, but still something). So I wanted to push it here in some form. What do you think about it?

### CODE REVIEW

**Comment by laughedelic** [comment]
I've moved here the history of that repo, so when you merge it, the content will be replaced, but the history will be appended. I suggest to merge this and then open issues with the plans for improvements.

**Comment by david-christiansen** [comment]
Laughadelic: I can give you permissions to transfer repositories - do you still want it?

**Comment by laughedelic** [comment]
@david-christiansen thanks, but I think it's not needed already. Once this PR is merged, we will have everything here :ok_hand:

**Comment by jfdm** [comment]
@laughedelic Do you have the rights to have this PR merged, or do you have a known sponser who can merge it for you? If not I can merge it, and look to giving you rights for this project.

**Comment by laughedelic** [comment]
@jfdm yes, I can merge it. I think I have full access to this repo (except of settings). 
This PR is nothing special, I just wanted @melted to see it first, as he was the original author of this repo.

**Comment by melted** [comment]
It looks fine!

**Comment by puffnfresh** [comment]
:+1:

**Pull request merged**
